README.md
[Preview proposed readme](https://github.com/Subskii/first-contributions/tree/update-readme)
=> update readme to capture contributor per file convention

first-contributions/subskii.md
=> add subskii

first-contributions/Christopher-Stevers.md
=> add Christopher-Stevers

first-contributions/ArchaeotheriumSapienter.md
=> add ArchaeotheriumSapienter

first-contributions/Nahdus.md
=> add Nahdus

bharat-patodi.md
=> Add bharat-patodi

linhguinii.md
=> add linhguinii

first-contributions/AnthonyRod.md
=> add yanyamz

first-contributions/David-Amateau.md
=> add David-Amateau

first-contributions/srijani07.md
=> add srijani07

first-contributions/DeviousLab.md
=> add DeviousLab

first-contributions/Salman-Asif.md
=> add Salman-Asif

first-contributions/ravicandra-C.md
=> add Ravichandra-C

first-contributions/vignesh-ponraj.md
=> add vignesh-ponraj

first-contributions/Kokoaono.md
=> add kokoaono

first-contributions/rajeshkumarrs.md, rajeshkumarrs.md
=> add rajeshkumarrs

first-contributions/Tangjas20.md
=> add Tangjas20

first-contributions/olsson17.md
=> add olsson17

README.md
The credits for the idea, and the content completely goes to first-contribution repository. We, at The Fast Tracked Programmer, absolutely loved their implementation of first-contributions project and decided to implement it for the participants of the Open-Source challenge.
We decided to add a small enhancement to the already existing idea. We decided to pair the first contributions with a kanban board within Github. Additionally, since our mission is to get people to make meaningful Open-Source Pull-Requests, we decided to use the markdown files people push onto the first-contributions folder to act as an online resume where they can document their contributions to Open-Source. We decided to erase the commit history so that the particular folder inside this repository would be easy to …
=> Credits and organising the folder.

first-contributions/PuneetDabral.md
=> add PuneetDabral

first-contributions/Kit-Kate, first-contributions/Kit-Kate.md
=> Add Kit-Kate

first-contributions/SaNsK11.md
=> add SaNsK11

first-contributions/hello-adi.md
=> add hello-adi

first-contributions/abhaygupta08.md
=> add-abhaygupta08

profiles/bedrock-adam.md
Reverts the-fast-tracked-programmer/close-my-first-issue#110
=> Revert "add bedrock-adam"

profiles/bedrock-adam.md
=> add bedrock-adam

profiles/azainayub.md
=> Add azainayub

profiles/dwivedi-ritik.md
=> add dwivedi-ritik

profiles/jonas-lundahl.md
=> add jonas-lundahl

profiles/keshiki808.md
=> add-keshiki808

profiles/AndrewFrauens.md
=> add AndrewFrauens

profiles/okronoss.md
=> add okronoss

profiles/deanmsands3.md
=> add deanmsands3

profiles/jesperobb.md
=> add jesperobb

profiles/MadhavVij.md
Signed-off-by: Madhav Vij <madhav13vij@gmail.com>
closes #191
=> add MadhavVij

profiles/rguptan.md
=> add rguptan.md  closes #194

profiles/Terricing.md
=> add Terricing

profiles/Dummdevka.md
=> add Dummdevka

profiles/codebuddy.md
closes #204 and added codebuddy
=> add-codebuddy

profiles/harsha-helix.md
=> add harsha-helix

profiles/xyqshelly.md
=> add xyqshelly

profiles/Vastagon.md
=> add Vastagon

profiles/john-oreva.md
=> john-oreva

profiles/MiguelCiulog.md
=> add MiguelCiulog

profiles/suited-1.md
=> add suited-1

profiles/cherfim.md
=> add cherfim

profiles/dmcconeghy.md
=> add dmcconeghy

profiles/Ali-Nasrolahi.md
=> Added my md

profiles/pasandevin.md
=> add pasandevin

profiles/krishanshamod.md
=> add krishanshamod

profiles/HasiniSama.md
=> hasinisama

profiles/RealisticTheory.md
=> RealisticTheory

profiles/Anttonioo.md
=> add Anttonioo

profiles/killerfridge.md
=> add killerfridge

profiles/Giancarlo1021.md
=> add Giancarlo1021

profiles/dccabao.md
=> add dccabao

profiles/makeevolution.md
=> add makeevolution

profiles/Bernardo007jr.md
=> add Bernardo007jr

profiles/sulaimanq99.md
=> sulaimanq99

profiles/ETSnider.md
=> add ETSnider

profiles/ethanshamilton.md
=> add ethanshamilton

profiles/enzomdev.md
=> add enzomdev

profiles/lwskosa.md
=> add lwskosa

profiles/kabiirrr.md
=> add kabiirrr

profiles/Ribiper.md
=> add Ribiper

profiles/dragonbiketoursvn.md
=> add dragonbiketoursvn

profiles/adityaganeshKUL.md
=> add adityaganeshKUL

profiles/kingmathers92.md
=> kingmathers92

profiles/tanujshriyan.md
=> Add tanujshriyan

profiles/heikergil.md
=> add-heikergil

profiles/paper-skye.md
=> add paper-skye

profiles/lucasmatheus7.md
=> add lucasmatheus7

profiles/NeptuneIX.md
=> Add NeptuneIX

profiles/spartanharvey.md
=> spartanHarvey

profiles/kehshiba.md
=> add kehshiba

profiles/Oliver-BG.md
=> Add oliver bg

profiles/william-golovlev.md
=> add william-golovlev

profiles/Mocarram.md
=> add Mocarram

profiles/ASimpleCodingHermit.md
=> add ASimpleCodingHermit

profiles/brunohhomem.md
=> add brunohomem

profiles/sikehome.md
=> Add sikehome
